- name: Configure Docker and Deploy Container on EC2 Instances
  hosts: all
  become: true
  connection: ssh

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Deploy Docker container
      docker_container:
        name: medicure_app
        image: shubhamkushwah123/medicure:1.0
        state: started
        restart_policy: always
        ports:
          - "8084:8082"

