apiVersion: v1
kind: Config
clusters:
- name: kubernetes
  cluster:
    server: https://172.31.39.129:6443
    certificate-authority-data: Cg==
users:
- name: jenkins-user
  user:
    token: 
contexts:
- name: jenkins-context
  context:
    cluster: kubernetes
    user: jenkins-user
    namespace: default
current-context: jenkins-context
